 insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("노트북", "Notebook", 1000000, "LG", 50, "LG gram")
 insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("운동화", "stuff", 130000, "나이키", 200, "에어맥스")
 insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("마우스", "stuff", 10000, "logitech", 500, "무소음 마우스")
 insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("가방", "stuff", 300000, "앨리스 마샤", 70, "크로스 백")
 insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("아이폰", "Electronics", 1000000, "애플", 600, "아이폰 se2")
 insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("갤럭시탭", "Electronics", 400000, "삼성", 90, "최신형 태블릿")
 insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("펜", "stuff", 5000, "시그노", 3000, "잉크 펜")
 insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("원피스", "stuff", 120000, "LYNN", 10, "롱 원피스")
 insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("핸드폰 충전기", "stuff", 10000, "다이소", 40, "c 핀")
 insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("티비", "Electronics", 500000, "삼성", 15, "최신형")